### ISSUE TITLE
play sdp with VLC

### ISSUE THREAD

**Issue by coocoowow** [u10116032/Bebop2-C-SDK#1]
Hi, I am the student of NTUT , I compile your project and I can control the bebop2 .When I input v(send Video Enable Command), and play sdp file by VLC ,but there is not any stream.
Is there anything I missunderstand or maybe the firmware of bebop is different?

![image](https://user-images.githubusercontent.com/30278144/33239219-04caa664-d2d8-11e7-9f4b-b9179e377f7d.png)

**Comment by u10116032** [comment]
@coocoowow 
Hi, I just checked the code and it still works fine for me.

First of all, please checkout the firewall of your PC. If it can be controlled correctly, the streaming data will be transmitted via UDP port 55004, please checkout if it is blocked or not.

Second, you can send more times of videoEnable command since it is transmitted through UDP port, which means the package may be dropped while transmitted.(Though I think that it's not possible...)

Third, please checkout the firmware version of your bebop2. I remember that there are some changes 
 about streaming protocol in different firmware version. 

If there are still some problems, please let me know, I will try my best to solve it :)

**Comment by coocoowow** [comment]
Hi, I just turn off firewall and I check port 55004 by Wireshark , it is not blocked.
My bebop2 firmware version is 4.0.5, may you tell me what is your bebop2 firmware version?

thanks

**Comment by u10116032** [comment]
Sorry that I just left my device in my lab. I remember that the version is 3.x.x.

Here is some information about streaming which was asked by me few months ago.

http://forum.developer.parrot.com/t/the-arg-of-pcmd-timestampandseqnum/5197/11

The developer said that the first version might be deprecated...

Maybe you can change to use the protocol in v2

By the way, have you ever tried to open the vlc file after sending videoEnable?

**Comment by coocoowow** [comment]
Hi, I remember something, when I download your project and try to compile it, but it is not done because I lost AssemblyInfo.cs. When I delete it from Visual studio , I can compile it successfully.
Is this situation cause this problem?
![image](https://user-images.githubusercontent.com/30278144/33241189-db49388a-d2fc-11e7-886e-77df056c7a8f.png)

**Comment by u10116032** [comment]
@coocoowow 
Hi, I had this issue, too. All you did was same as me, AssemblyInfo.cs seems like it's not important. If you miss that file, you can create it by yourself or just remove it. 

Besides, if you can control the drone successfully, I think the code works fine. The only problem is about VLC and bebop2 streaming protocol.

**Comment by coocoowow** [comment]
Hi, I solve this problem, I found that the reason is VLC version.
Now , I can play sdp by VLC(1.1.5).
thank you
